# Generated by Django 4.2 on 2024-06-29 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('permission_module', models.CharField(blank=True, max_length=255, null=True)),
                ('can_add', models.BooleanField(blank=True, default=False, null=True)),
                ('can_update', models.BooleanField(blank=True, default=False, null=True)),
                ('can_list', models.BooleanField(blank=True, default=False, null=True)),
                ('can_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('can_do_all', models.BooleanField(blank=True, default=False, null=True)),
                ('can_assign_permission', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='account.role')),
            ],
            options={
                'verbose_name_plural': 'User Role Permissions',
                'unique_together': {('role', 'permission_module')},
            },
        ),
    ]
