# Generated by Django 4.2 on 2024-07-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userrolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrolepermission',
            name='can_list_log',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
