# Generated by Django 5.0.6 on 2024-05-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_warehouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WareHouse',
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
