# Generated by Django 5.0.6 on 2024-06-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WareHouse',
        ),
    ]
