# Generated by Django 4.2 on 2024-06-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_role_role_name_alter_role_status'),
        ('account', '0009_delete_warehouse'),
    ]

    operations = [
    ]
