# Generated by Django 4.2 on 2024-06-14 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('product_size', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('product_status', models.CharField(blank=True, choices=[('CHECKED-IN', 'CHECKED-IN'), ('CHECKED-OUT', 'CHECKED-OUT')], max_length=255, null=True)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('emc_number', models.CharField(blank=True, max_length=255, null=True)),
                ('model_family', models.CharField(blank=True, max_length=255, null=True)),
                ('memory', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_type', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_size', models.CharField(blank=True, max_length=255, null=True)),
                ('battery_capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('battery_cycles', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_notes', models.TextField(blank=True, null=True)),
                ('technical_notes', models.TextField(blank=True, null=True)),
                ('track_pad', models.BooleanField(default=False, null=True)),
                ('keyboard', models.BooleanField(default=False, null=True)),
                ('lcd_ghost_peel', models.BooleanField(default=False, null=True)),
                ('headphone_jack', models.BooleanField(default=False, null=True)),
                ('microphone', models.BooleanField(default=False, null=True)),
                ('usb_port', models.BooleanField(default=False, null=True)),
                ('bluetooth_wifi', models.BooleanField(default=False, null=True)),
                ('face_time_camera', models.BooleanField(default=False, null=True)),
                ('find_my_mac', models.BooleanField(default=False, null=True)),
                ('mdm', models.BooleanField(default=False, null=True)),
                ('bar_code', models.FileField(blank=True, null=True, upload_to='bar_code/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse_name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'WareHouse',
            },
        ),
        migrations.CreateModel(
            name='WipingQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('data_wiped', models.BooleanField(blank=True, default=False, null=True)),
                ('software_used', models.TextField(blank=True, null=True)),
                ('software_reason', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiping_product', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Wiping Questionnair',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('type', models.CharField(blank=True, choices=[('default', 'default'), ('uploded', 'uploded')], max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Product Image',
            },
        ),
        migrations.CreateModel(
            name='ProductCheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_moved_to', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_checkout', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Product Checkout',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_warehouse', to='product.warehouse'),
        ),
    ]
