# Generated by Django 4.2 on 2024-06-03 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('product_size', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('product_status', models.CharField(blank=True, choices=[('CHECKED-IN', 'CHECKED-IN'), ('CHECKED-OUT', 'CHECKED-OUT')], max_length=255, null=True)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('emc_number', models.CharField(blank=True, max_length=255, null=True)),
                ('model_family', models.CharField(blank=True, max_length=255, null=True)),
                ('memory', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_type', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_size', models.CharField(blank=True, max_length=255, null=True)),
                ('battery_capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('battery_cycles', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_notes', models.TextField(blank=True, null=True)),
                ('technical_notes', models.TextField(blank=True, null=True)),
                ('track_pad', models.BooleanField(default=False, null=True)),
                ('keyboard', models.BooleanField(default=False, null=True)),
                ('lcd_ghost_peel', models.BooleanField(default=False, null=True)),
                ('headphone_jack', models.BooleanField(default=False, null=True)),
                ('microphone', models.BooleanField(default=False, null=True)),
                ('usb_port', models.BooleanField(default=False, null=True)),
                ('bluetooth_wifi', models.BooleanField(default=False, null=True)),
                ('face_time_camera', models.BooleanField(default=False, null=True)),
                ('find_my_mac', models.BooleanField(default=False, null=True)),
                ('mdm', models.BooleanField(default=False, null=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_warehouse', to='product.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Product Image',
            },
        ),
    ]
