# Generated by Django 4.2 on 2024-06-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='apple_care',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
