# Generated by Django 4.2 on 2024-07-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lcd_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='employee_signature/'),
        ),
    ]
