# Generated by Django 4.2 on 2024-07-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wipingquestionnaire',
            options={'verbose_name_plural': 'Product Checkin (Wiping Questionnair)'},
        ),
        migrations.RemoveField(
            model_name='productcheckout',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='wipingquestionnaire',
            name='signature',
        ),
        migrations.AddField(
            model_name='productcheckout',
            name='checkout_signature',
            field=models.ImageField(blank=True, null=True, upload_to='employee_checkout_signature/'),
        ),
        migrations.AddField(
            model_name='wipingquestionnaire',
            name='checkin_signature',
            field=models.ImageField(blank=True, null=True, upload_to='employee_checkin_signature/'),
        ),
    ]
