# Generated by Django 4.2 on 2024-06-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bar_code',
            field=models.FileField(blank=True, null=True, upload_to='bar_code/'),
        ),
    ]
