# Generated by Django 4.2 on 2024-07-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_lcd_grade_product_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='signature',
        ),
        migrations.AddField(
            model_name='productcheckout',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='employee_signature/'),
        ),
        migrations.AddField(
            model_name='wipingquestionnaire',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='employee_signature/'),
        ),
    ]
