# Generated by Django 4.2 on 2024-07-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_signature_productcheckout_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcheckout',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='wipingquestionnaire',
            name='signature',
        ),
        migrations.AddField(
            model_name='productcheckout',
            name='checkout_signature',
            field=models.ImageField(blank=True, null=True, upload_to='employee_checkout_signature/'),
        ),
        migrations.AddField(
            model_name='wipingquestionnaire',
            name='checkin_signature',
            field=models.ImageField(blank=True, null=True, upload_to='employee_checkin_signature/'),
        ),
    ]
