# Generated by Django 4.2 on 2024-06-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_bar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='product_image/default_product_image.jpg', null=True, upload_to='product_image/'),
        ),
    ]
