# Generated by Django 4.2 on 2024-06-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_bar_code_product_created_by_and_more'),
        ('product', '0004_alter_product_bar_code'),
    ]

    operations = [
    ]
