# Generated by Django 4.2 on 2024-06-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='type',
            field=models.CharField(blank=True, choices=[('default', 'default'), ('uploaded', 'uploaded')], max_length=200, null=True),
        ),
    ]
