# Generated by Django 4.2 on 2024-06-21 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bar_code_number',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProductCheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_moved_to', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_checkout', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Product Checkout',
            },
        ),
    ]
